theme: jekyll-theme-tactile
title: Animal traits database
description: A curated and open database of terrestrial animal traits
csv_url: "_observations.csv"
github:
  is_user_page: false
  is_project_page: false
