theme: jekyll-theme-tactile
title: AnimalTraits
description: A curated and open database of terrestrial animal traits
url: "https://animaltraits.org"
csv_url: "observations.csv"
xlsx_url: "observations.xlsx"
docs_url: "column-documentation.csv"

github:
  is_user_page: false
  is_project_page: false

